services:
  jupyter-ai-agent:
    build:
      context: .
      dockerfile: ./jupyter_ai_agent
    image: jupyter-ai-agent:0.1
    container_name: jupyter-ai-agent
    ports:
      - "8000:8000"  # FastAPI 服务端口
    env_file:
      - .env
    environment:
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./notebooks:/app/notebooks
    networks:
      - jupyter-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  jupyter-ai-extensions:
    build: ./jupyter_ai_extensions
    image: jupyter-ai-extensions:0.1
    env_file:
      - .env
    container_name: jupyter-ai-extensions
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - AI_AGENT_URL=${AI_AGENT_URL}
    volumes:
      - ./notebooks:/app/notebooks
    networks:
      - jupyter-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  jupyter-network:
    name: jupyter-network
    external: true
